### PR TITLE
Port to 1.10.x

### PR DESCRIPTION
**Pull request by 3TUSK**
Self-explained title...

### CODE REVIEW

**Comment by 3TUSK** [comment]
In case it does matter: all contents in these three commits are considered as in public domain.

**Comment by zlainsama** [comment]
Thank you.
If you are willing to take this mod for me and maintain or develop it, I can transfer the ownership to you. @3TUSK

**Comment by 3TUSK** [comment]
Isn't this mod developed for Bilicraft server?
Also, as a 12th grade high school student, I am afraid that I dont have enough time on development...

**Comment by zlainsama** [comment]
Yes, but nobody contacted me since then.
Okay, it's fine, don't worry about this.
Thank you.

**Pull request merged**
